#!/bin/bash

# Check if a filename is provided as an argument
if [ $# -ne 1 ]; then
    echo "Usage: $0 <file_to_send>"
    exit 1
fi

# File to send is the first argument
file_to_send="$1"

# Remote server details
remote_username="b9384928dc6d"
remote_server="b9384928dc6d.82b1359d.alx-cod.online"
remote_directory="~"

# Use scp to send the file to the remote server
scp "$file_to_send" "${remote_username}@${remote_server}:${remote_directory}"

# Check the exit status of scp
if [ $? -eq 0 ]; then
    echo "File sent successfully to ${remote_server}:${remote_directory}"
else
    echo "Failed to send the file to ${remote_server}:${remote_directory}"
fi

